dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install: npm install -g mocha && npm install -g typescript
install: npm install
script:
  - npm run fmt
  - npm run build
  - npm run test
  - npm run clean-backups
