dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install: npm install -g truffle mocha typescript ganache-cli
install: npm install

before_script:
  - ganache-cli -m "shove afford modify census bridge good random error fault floor fringe oblige" -i 1002 > /dev/null &
  - sleep 5
script:
  - npm run deploy-eac
  - npm run build
  - npm run test
  - npm run clean-backups

matrix:
  fast_finish: true
  include:
  - env: RUN_ONLY_OPTIONAL_TESTS=false
  - env: RUN_ONLY_OPTIONAL_TESTS=true
  - env: JUST_LINT=true
    before_install: true
    before_script: true
    script: npm run lint
  allow_failures:
  - env: RUN_ONLY_OPTIONAL_TESTS=true
  - env: JUST_LINT=true