dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install: npm install -g truffle
install: npm install

before_script:
  - npm run ganache > /dev/null &
  - sleep 5
script:
  - npm run deploy-eac
  - npm run build
  - npm run test

matrix:
  fast_finish: true
  include:
    - before_install: true
      before_script: true
      script: npm run lint
    - env: RUN_ONLY_OPTIONAL_TESTS=false
    - env: RUN_ONLY_OPTIONAL_TESTS=true
  allow_failures:
  - env: RUN_ONLY_OPTIONAL_TESTS=true