dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install: npm install -g truffle mocha typescript ganache-cli
install: npm install
script:
  - npm run deploy-eac
  - npm run fmt
  - npm run build
  - npm run test
  - npm run clean-backups
before_script:
  - ganache-cli -m "shove afford modify census bridge good random error fault floor fringe oblige" -i 1002 > /dev/null &
  - sleep 5